//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmitForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_SUBMIT> TB_SUBMIT { get; set; }
        public DbSet<TB_COMENT> TB_COMENT { get; set; }
    
        public virtual int up_submit_insert(string name, string title, string contents, string hp1, string hp2, string hp3, string post_no, string adress1, string adress2, string birth_dt, ObjectParameter seq)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("contents", contents) :
                new ObjectParameter("contents", typeof(string));
    
            var hp1Parameter = hp1 != null ?
                new ObjectParameter("hp1", hp1) :
                new ObjectParameter("hp1", typeof(string));
    
            var hp2Parameter = hp2 != null ?
                new ObjectParameter("hp2", hp2) :
                new ObjectParameter("hp2", typeof(string));
    
            var hp3Parameter = hp3 != null ?
                new ObjectParameter("hp3", hp3) :
                new ObjectParameter("hp3", typeof(string));
    
            var post_noParameter = post_no != null ?
                new ObjectParameter("post_no", post_no) :
                new ObjectParameter("post_no", typeof(string));
    
            var adress1Parameter = adress1 != null ?
                new ObjectParameter("adress1", adress1) :
                new ObjectParameter("adress1", typeof(string));
    
            var adress2Parameter = adress2 != null ?
                new ObjectParameter("adress2", adress2) :
                new ObjectParameter("adress2", typeof(string));
    
            var birth_dtParameter = birth_dt != null ?
                new ObjectParameter("birth_dt", birth_dt) :
                new ObjectParameter("birth_dt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_submit_insert", nameParameter, titleParameter, contentsParameter, hp1Parameter, hp2Parameter, hp3Parameter, post_noParameter, adress1Parameter, adress2Parameter, birth_dtParameter, seq);
        }
    
        public virtual ObjectResult<up_submit_selectList_Result> up_submit_selectList(Nullable<int> rowsPerPage, Nullable<int> pageNumber, Nullable<byte> search_type, string search_text, Nullable<byte> rank_type, ObjectParameter totalRecords)
        {
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("rowsPerPage", rowsPerPage) :
                new ObjectParameter("rowsPerPage", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var search_typeParameter = search_type.HasValue ?
                new ObjectParameter("search_type", search_type) :
                new ObjectParameter("search_type", typeof(byte));
    
            var search_textParameter = search_text != null ?
                new ObjectParameter("search_text", search_text) :
                new ObjectParameter("search_text", typeof(string));
    
            var rank_typeParameter = rank_type.HasValue ?
                new ObjectParameter("rank_type", rank_type) :
                new ObjectParameter("rank_type", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_submit_selectList_Result>("up_submit_selectList", rowsPerPageParameter, pageNumberParameter, search_typeParameter, search_textParameter, rank_typeParameter, totalRecords);
        }
    
        public virtual ObjectResult<up_submit_list_Result> up_submit_list(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_submit_list_Result>("up_submit_list", nameParameter);
        }
    
        public virtual ObjectResult<up_submit_selectdetail_Result> up_submit_selectdetail(Nullable<int> seq)
        {
            var seqParameter = seq.HasValue ?
                new ObjectParameter("seq", seq) :
                new ObjectParameter("seq", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_submit_selectdetail_Result>("up_submit_selectdetail", seqParameter);
        }
    
        public virtual int up_submit_selectupdate(Nullable<int> seq, string name, string title, string contents, string hp1, string hp2, string hp3, string post_no, string adress1, string adress2, string birth_dt)
        {
            var seqParameter = seq.HasValue ?
                new ObjectParameter("seq", seq) :
                new ObjectParameter("seq", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var contentsParameter = contents != null ?
                new ObjectParameter("contents", contents) :
                new ObjectParameter("contents", typeof(string));
    
            var hp1Parameter = hp1 != null ?
                new ObjectParameter("hp1", hp1) :
                new ObjectParameter("hp1", typeof(string));
    
            var hp2Parameter = hp2 != null ?
                new ObjectParameter("hp2", hp2) :
                new ObjectParameter("hp2", typeof(string));
    
            var hp3Parameter = hp3 != null ?
                new ObjectParameter("hp3", hp3) :
                new ObjectParameter("hp3", typeof(string));
    
            var post_noParameter = post_no != null ?
                new ObjectParameter("post_no", post_no) :
                new ObjectParameter("post_no", typeof(string));
    
            var adress1Parameter = adress1 != null ?
                new ObjectParameter("adress1", adress1) :
                new ObjectParameter("adress1", typeof(string));
    
            var adress2Parameter = adress2 != null ?
                new ObjectParameter("adress2", adress2) :
                new ObjectParameter("adress2", typeof(string));
    
            var birth_dtParameter = birth_dt != null ?
                new ObjectParameter("birth_dt", birth_dt) :
                new ObjectParameter("birth_dt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_submit_selectupdate", seqParameter, nameParameter, titleParameter, contentsParameter, hp1Parameter, hp2Parameter, hp3Parameter, post_noParameter, adress1Parameter, adress2Parameter, birth_dtParameter);
        }
    
        public virtual int up_submit_selectdelete(Nullable<int> seq)
        {
            var seqParameter = seq.HasValue ?
                new ObjectParameter("seq", seq) :
                new ObjectParameter("seq", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_submit_selectdelete", seqParameter);
        }
    
        public virtual int up_coment_insert(Nullable<int> submit_seq, string coment)
        {
            var submit_seqParameter = submit_seq.HasValue ?
                new ObjectParameter("submit_seq", submit_seq) :
                new ObjectParameter("submit_seq", typeof(int));
    
            var comentParameter = coment != null ?
                new ObjectParameter("coment", coment) :
                new ObjectParameter("coment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_coment_insert", submit_seqParameter, comentParameter);
        }
    
        public virtual ObjectResult<up_coment_select_list_Result> up_coment_select_list(Nullable<int> submit_seq, Nullable<int> rowsPerPage, Nullable<int> pageNumber, ObjectParameter totalRecords)
        {
            var submit_seqParameter = submit_seq.HasValue ?
                new ObjectParameter("submit_seq", submit_seq) :
                new ObjectParameter("submit_seq", typeof(int));
    
            var rowsPerPageParameter = rowsPerPage.HasValue ?
                new ObjectParameter("rowsPerPage", rowsPerPage) :
                new ObjectParameter("rowsPerPage", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_coment_select_list_Result>("up_coment_select_list", submit_seqParameter, rowsPerPageParameter, pageNumberParameter, totalRecords);
        }
    }
}
